// Copyright AetherFX.
//
// Checks the five materials generated by engines/unreal/scripts/generate_materials.py
// into /AetherFX/Materials: that they exist (so the runtime is not silently
// falling back to the engine default), that their domain / blend mode /
// shading model are what the bridge assumes, and that every shader parameter
// UAetherFXComponent sets at runtime is actually present.
//
// This is the test that catches a regenerated or hand-edited material that no
// longer matches the C++ side.

#include "Misc/AutomationTest.h"

#if WITH_DEV_AUTOMATION_TESTS

#include "AetherFXResources.h"
#include "AetherFXTypes.h"

#include "Materials/Material.h"
#include "Materials/MaterialInterface.h"
#include "UObject/UObjectGlobals.h"

IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FAetherFXGeneratedMaterialsTest,
	"AetherFX.Materials.Generated",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::ClientContext |
	EAutomationTestFlags::CommandletContext | EAutomationTestFlags::ProductFilter)

bool FAetherFXGeneratedMaterialsTest::RunTest(const FString& Parameters)
{
	struct FExpectation
	{
		const TCHAR* AssetPath;
		EMaterialDomain Domain;
		EBlendMode Blend;
		EMaterialShadingModel ShadingModel;
		bool bNeedsInstancedStaticMeshUsage;
	};

	const FExpectation Expectations[] =
	{
		{ TEXT("/AetherFX/Materials/M_AetherFX_Billboard_Additive.M_AetherFX_Billboard_Additive"),
		  MD_Surface, BLEND_Additive, MSM_Unlit, true },
		{ TEXT("/AetherFX/Materials/M_AetherFX_Billboard_Translucent.M_AetherFX_Billboard_Translucent"),
		  MD_Surface, BLEND_Translucent, MSM_Unlit, true },
		{ TEXT("/AetherFX/Materials/M_AetherFX_Mesh.M_AetherFX_Mesh"),
		  MD_Surface, BLEND_Masked, MSM_DefaultLit, true },
		{ TEXT("/AetherFX/Materials/M_AetherFX_Decal.M_AetherFX_Decal"),
		  MD_DeferredDecal, BLEND_Translucent, MSM_DefaultLit, false },
		{ TEXT("/AetherFX/Materials/M_AetherFX_Ribbon.M_AetherFX_Ribbon"),
		  MD_Surface, BLEND_AlphaComposite, MSM_Unlit, false },
	};

	UMaterialInterface* EngineDefault = UMaterial::GetDefaultMaterial(MD_Surface);

	for (const FExpectation& Expectation : Expectations)
	{
		const FString Label = FPaths::GetBaseFilename(FString(Expectation.AssetPath));

		UMaterial* Material = LoadObject<UMaterial>(nullptr, Expectation.AssetPath);
		if (!TestNotNull(*FString::Printf(TEXT("%s exists"), *Label), Material))
		{
			AddError(FString::Printf(
				TEXT("%s is missing. Run engines/unreal/scripts/generate_materials.py through ")
				TEXT("UnrealEditor-Cmd (see docs/UNREAL.md, 'Materials')."), *Label));
			continue;
		}

		TestNotEqual(*FString::Printf(TEXT("%s is not the engine default"), *Label),
			static_cast<UMaterialInterface*>(Material), EngineDefault);

		TestEqual(*FString::Printf(TEXT("%s domain"), *Label),
			static_cast<int32>(Material->MaterialDomain.GetValue()), static_cast<int32>(Expectation.Domain));
		TestEqual(*FString::Printf(TEXT("%s blend mode"), *Label),
			static_cast<int32>(Material->GetBlendMode()), static_cast<int32>(Expectation.Blend));

		if (Expectation.Domain == MD_Surface)
		{
			TestTrue(*FString::Printf(TEXT("%s shading model"), *Label),
				Material->GetShadingModels().HasShadingModel(Expectation.ShadingModel));
		}

		if (Expectation.bNeedsInstancedStaticMeshUsage)
		{
			TestTrue(*FString::Printf(TEXT("%s is usable with instanced static meshes"), *Label),
				Material->GetUsageByFlag(MATUSAGE_InstancedStaticMeshes));
		}

		// Every parameter the component pokes at runtime must exist, otherwise
		// SetScalar/Vector/TextureParameterValue is a silent no-op.
		TArray<FMaterialParameterInfo> ScalarInfo, VectorInfo, TextureInfo;
		TArray<FGuid> Ids;
		Material->GetAllScalarParameterInfo(ScalarInfo, Ids);
		Material->GetAllVectorParameterInfo(VectorInfo, Ids);
		Material->GetAllTextureParameterInfo(TextureInfo, Ids);

		auto Has = [](const TArray<FMaterialParameterInfo>& Infos, FName Name)
		{
			return Infos.ContainsByPredicate([Name](const FMaterialParameterInfo& Info) { return Info.Name == Name; });
		};

		TestTrue(*FString::Printf(TEXT("%s has the BaseTexture parameter"), *Label),
			Has(TextureInfo, AetherFX::MaterialParams::BaseTexture));
		TestTrue(*FString::Printf(TEXT("%s has the BaseColor parameter"), *Label),
			Has(VectorInfo, AetherFX::MaterialParams::BaseColor));
		TestTrue(*FString::Printf(TEXT("%s has the Opacity parameter"), *Label),
			Has(ScalarInfo, AetherFX::MaterialParams::Opacity));
		TestTrue(*FString::Printf(TEXT("%s has the EmissiveIntensity parameter"), *Label),
			Has(ScalarInfo, AetherFX::MaterialParams::EmissiveIntensity));

		if (Material->GetBlendMode() == BLEND_AlphaComposite)
		{
			TestTrue(*FString::Printf(TEXT("%s has the Additive parameter"), *Label),
				Has(ScalarInfo, AetherFX::MaterialParams::Additive));
		}
		if (Expectation.ShadingModel == MSM_DefaultLit && Expectation.Domain == MD_Surface)
		{
			TestTrue(*FString::Printf(TEXT("%s has the FresnelPower parameter"), *Label),
				Has(ScalarInfo, AetherFX::MaterialParams::FresnelPower));
		}
	}

	// The runtime accessors must hand back the generated assets, not a fallback.
	TestNotEqual(TEXT("Materials::BillboardAdditive() resolves"), AetherFX::Materials::BillboardAdditive(), EngineDefault);
	TestNotEqual(TEXT("Materials::BillboardTranslucent() resolves"), AetherFX::Materials::BillboardTranslucent(), EngineDefault);
	TestNotEqual(TEXT("Materials::Mesh() resolves"), AetherFX::Materials::Mesh(), EngineDefault);
	TestNotEqual(TEXT("Materials::Decal() resolves"), AetherFX::Materials::Decal(), EngineDefault);
	TestNotEqual(TEXT("Materials::Ribbon() resolves"), AetherFX::Materials::Ribbon(), EngineDefault);

	// The unit quad every billboard system instances must build.
	TestNotNull(TEXT("unit quad static mesh"), AetherFX::GetUnitQuadMesh());

	return true;
}

#endif // WITH_DEV_AUTOMATION_TESTS
