# aether_add_module(<name> SOURCES ... DEPS ...)
# Creates static library aether_<name> with public include dir
# src/<name>/include and applies project-wide warnings.
function(aether_set_warnings target)
  if(MSVC)
    target_compile_options(${target} PRIVATE /W4 /permissive- /Zc:__cplusplus /utf-8)
    if(AETHER_WARNINGS_AS_ERRORS)
      target_compile_options(${target} PRIVATE /WX)
    endif()
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Wshadow -Wno-unused-parameter)
    if(AETHER_WARNINGS_AS_ERRORS)
      target_compile_options(${target} PRIVATE -Werror)
    endif()
  endif()
  # determinism: never fast-math
  if(NOT MSVC)
    target_compile_options(${target} PRIVATE -fno-fast-math -ffp-contract=off)
  endif()
endfunction()

function(aether_add_module name)
  cmake_parse_arguments(ARG "" "" "SOURCES;DEPS" ${ARGN})
  set(target aether_${name})
  if(NOT ARG_SOURCES)
    # Module has no implementation yet: keep the build graph valid.
    set(placeholder "${CMAKE_BINARY_DIR}/placeholders/${name}_placeholder.cpp")
    file(WRITE "${placeholder}" "namespace aether { int aether_${name}_placeholder = 0; }\n")
    set(ARG_SOURCES "${placeholder}")
  endif()
  add_library(${target} STATIC ${ARG_SOURCES})
  add_library(aether::${name} ALIAS ${target})
  target_include_directories(${target} PUBLIC
    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>)
  if(ARG_DEPS)
    target_link_libraries(${target} PUBLIC ${ARG_DEPS})
  endif()
  aether_set_warnings(${target})
  set_target_properties(${target} PROPERTIES FOLDER "aether")
endfunction()
